### ISSUE TITLE
Bot doesn't buy

### ISSUE THREAD

**Issue by FOXGLove81** [chrisleekr/binance-trading-bot#110]
Bot doesn't buy from me at all. It seems that something is wrong with the settings. All are selected by default.
Who can share good working settings?
And also, I noticed that the frontend hangs and does not update the data.

**Comment by chrisleekr** [comment]
Hi @FOXGLove81 

> And also, I noticed that the frontend hangs and does not update the data.


Have you checked the log?
https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by FOXGLove81** [comment]
Haven't run anymore. I am already testing the branch feature-monitoring-simultaneously.
The question about the settings remains open for me.

**Comment by chrisleekr** [comment]
>Haven't run anymore. I am already testing the branch feature-monitoring-simultaneously.

Cool. Let me know if have any issue with that, please leave feedback in the PR.

> The question about the settings remains open for me.

For the settings, I don't think anyone will recommend or suggest because it's your money, your responsibility.
Many people have different settings based on their strategy. 

As the logic is pretty simple, you can find/calculate/test your settings. 
Each coin would have a different trend; hence, you better customise the setting per the coin.

I tried my best to explain how it works in README.md - https://github.com/chrisleekr/binance-trading-bot#how-it-works
Please let me know if it is not clear for you.

**Comment by chrisleekr** [comment]
@FOXGLove81 If this is no longer issue, please close the issue. :)

**Comment by chrisleekr** [comment]
As I didn't hear from you, I close the issue. If you have another issue, open a new issue, please.
