### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by AlexVanchov** [chrisleekr/binance-trading-bot#209]
Hello. I have some questions about the app.
How can I config which pairs I want to use?
Why when I am using testate I can't remove default bot pairs?
Is there something like backtesting?
Also my ETHUSDT position isn't changing the "Estimated Value", so it's not getting right the current pair value. Some pairs "Action" isn't changing too

**Comment by pedrohusky** [comment]
> How can I config which pairs I want to use?

After setup the bot, go to frontend and then click the setting button top at right corner, then remove or add the symbols you want.

> Why when I am using testate I can't remove default bot pairs?

Just follow above directions.

> Is there something like backtesting?

Only the testnet.

> Also my ETHUSDT position isn't changing the "Estimated Value", so it's not getting right the current pair value. Some pairs "Action" isn't changing too

It could be because you are in testnet, in which you already have a lot of coins, then the bot won't buy (I guess you just need to config the max purchase amount to be higher than what you have) and won't sell because it don't have the last buy price (you can manually insert it).

**Comment by chrisleekr** [comment]
Thanks, @pedrohusky. 

I will close the issue @AlexVanchov 
Please create new issue if you have further questions.
