### ISSUE TITLE
UX issue with coin sorting 

### ISSUE THREAD

**Issue by Mahniex** [chrisleekr/binance-trading-bot#244]
Whilst sorting of various cryptos is useful, it can be very difficult to change settings when the coins jump around 

### Describe the solution you'd like

I'd like there to be a button which temporarily disables sorting

### Describe alternatives you've considered

 - Disable sorting completely
 - Disabling sorting on hover
 - Sorting by alphabetical order

### Additional context

N/A

**Comment by chrisleekr** [comment]
Hi @Mahniex 

I am aware of the issue. Since this issue is not a priority, I will eventually fix it. 
Thanks for reporting.

**Comment by hugoleosp** [comment]
I hope you reconsider the priority of this issue. When the market is volatile it's almost impossible to read the data from the coin, because every second it changes place.. It's one of the main reason I stopped using the bot.. (along with the excessive trading orders when price keeps changing a lot near the limit, it cancels/recreates dozen of orders in just a few seconds)

**Comment by chrisleekr** [comment]
Hi @hugoleosp 

Thanks for pointing out.

I am currently trying to implement the grid trade strategy as a priority. 
This implementation requires massive refactoring and testing. 

I will check out this change after.
