### ISSUE TITLE
Recommended settings

### ISSUE THREAD

**Issue by shanejones** [chrisleekr/binance-trading-bot#27]
Does anyone have any recommended settings?  I've had this running for some time now and not seeing any trades go through. _Maybe I'm just impatient_

Currently tracking USDT on the FIAT and on the Coin side DOGEUSDT VETUSDT ETHUSDT BTCUSDT

I have money in my USDT and I also have holdings in all of the coins above.

15 min candles on 5 candle limit
Max purchase 10
1.01  min profit 
0.99  stop price / limit

**Comment by chrisleekr** [comment]
Hey @shanejones 

I won't give you what settings to set. However, I want to point out things to note.

1. If you set `Max purchase amount` to $10 and the price declines, then the bot will remove the last buy price because you cannot place a sell order to Binance under $10.
2. If you set `Minimum profit percentage` to 1.01, it is likely you will lose the money because of the commission.
3. If you already have more than $10 worth of the coin, then the bot will not purchase even if it reaches the lowest price. However, you can set the last buy price manually, so the bot can sell the coin you hold.

**Comment by Maxoos** [comment]
@chrisleekr just to point out I also straggled understanding this when I started out. It forced me to look at the code which is actually great. Maybe a minimum of $15 for new users?

**Comment by chrisleekr** [comment]
@Maxoos 

I always set $100 (again, not recommending). 
I mean if the market falls rapidly, the coin will be easily worth less than $10 easily if set a lower amount to buy.

**Comment by shanejones** [comment]
Thanks. I can actually see it working now as I have some limit sell orders set up via the script.

Assuming no suitable buy opportunities have come in yet.

**Comment by chrisleekr** [comment]
As I have added a detail scenario for how it works, hence, I close the issue

- https://github.com/chrisleekr/binance-trading-bot#buy-signal
