### ISSUE TITLE
feat: auto-trigger buy should be rescheduled when the stop-loss executed.

### ISSUE THREAD

**Issue by arturoller** [chrisleekr/binance-trading-bot#316]
Hello, I have a problem with the STOP LOSS function. Software version: v0.0.78 (60a464a). I set STOP LOSS to 10% and everything works fine, when the rate goes down, creates an order and sells, but the problem appears a few minutes after selling. The bot immediately creates a purchase target and after 10 minutes it buys the currency again despite the "pause" icon displayed. The pause time is set to 360 minutes. 

I couldn't do the screenshoot because the bot bought the currency too quickly :(

**Comment by arturoller** [comment]
![Screenshot 2021-09-14 at 23-46-40 146 99 ｜ SOLBUSD Binance Spot](https://user-images.githubusercontent.com/60364852/133338445-44e93d11-9cb2-4268-b77e-9d8e6aca459c.png)

![Screenshot 2021-09-14 at 23-48-18 Binance Auto Trading Bot Dashboard](https://user-images.githubusercontent.com/60364852/133338508-b48b4c6f-05be-4601-8bf2-6be7609e045f.png)

**Comment by arturoller** [comment]
Maybe auto trigger buy triggers this order?

**Comment by ilbuonmarcio** [comment]
Is it active? How many minutes until autotriggering buy?

**Comment by chrisleekr** [comment]
Hi @arturoller 

You have auto-trigger buy enabled. That is why it was placing the order. So this is not a bug.

However, I think auto-trigger buy needs to be enhanced, which is raised by other traders as well.

So I guess the flow should be, when the auto-trigger buy is enabled, the bot should
  - it should automatically be rescheduled if the price is over the ATH.
  - it should automatically be rescheduled if the trading is at a halt due to stop-loss.
 
I will work on this later. 

I will change to enhancement, not a bug.

**Comment by chrisleekr** [comment]
I have added to the top of TODO list - https://github.com/chrisleekr/binance-trading-bot#changes--todo

**Comment by ilbuonmarcio** [comment]
I'll have a look on the code on the upcoming hours/days, and if I see that noone still took up and do it I'll try making a contribution here
