### ISSUE TITLE
Filled orders not applying in the bot

### ISSUE THREAD

**Issue by kaziqta** [chrisleekr/binance-trading-bot#33]
The issue is that the bot puts an order in a decent time, but after the order is filled, it doesn't start tracking it, it doesn't acknowledge that there is already a position to trade with. 

So after the bot buys and it is filled, it just ignores it.

**Comment by eyass445** [comment]
I have the same problem

**Comment by Maxoos** [comment]
I've tracked this to the point where the bot deletes the last-buy-price, there are two places where it happens. I don't know which one is the issue, however, I suspect it's because the balance calculation is done on old data. Sometime it works, sometimes it'll delete the last-buy-price. 

I have commented out the two places where the last-buy-price is deleted and it works fine, it just keeps the last-buy-price in the UI which I'm not too fussed about.

**Comment by chrisleekr** [comment]
@kaziqta 

I am not sure I understood the issue. The bot does not need to track the order as it is working based on the coin balance. 

Can you elaborate on what the actual issue is?

**Comment by kaziqta** [comment]
> @kaziqta
> 
> I am not sure I understood the issue. The bot does not need to track the order as it is working based on the coin balance.
> 
> Can you elaborate on what the actual issue is?

Sometimes, when it places an order and the order gets filled, nothing happens in regards to the bot, it ignores it.

**Comment by chrisleekr** [comment]
@kaziqta That kind of issue never happened to me yet. Without any log, I wouldn't be able to find what went wrong.

**Comment by kaziqta** [comment]
It may be something from a performance point of view, will check out logs, but nothing there for now.
