### ISSUE TITLE
Wrong profit

### ISSUE THREAD

**Issue by elvishp2006** [chrisleekr/binance-trading-bot#376]
## Version

v0.0.83
(366761b)

## Description

The bot saved a wrong profit for a coin pair

## Screenshots

![image](https://user-images.githubusercontent.com/7463100/139061573-dcdc4bfa-c95a-401c-b500-7cc086e63770.png)
![image](https://user-images.githubusercontent.com/7463100/139061603-9b496308-142d-48b0-8da3-65c63208c648.png)
## Additional context

The bot was running but was not using cpu on DigitalOcean
![image](https://user-images.githubusercontent.com/7463100/139061820-2e9620fb-0ecc-49ab-8ae5-2fadc2a869ec.png)
I executed the following commands to get it working again: 
docker-compose -f docker-compose.server.yml stop

docker-compose -f docker-compose.server.yml up -d

**Comment by chrisleekr** [comment]
@elvishp2006 

With the original issue, that looks very odd. How does the bot didn't record second buy grade?
You will need to provide me with logs if available. 
Click Logs for the symbol, find the log with the archived message, then click the "Data" icon of that message and give to me.
If it's not available now, when it happens again, please check the "Data" icon of that archived message.

Make sure your bot saves 1-2 days logs.


With 2nd issue that the trading view not getting the data, I haven't encountered that. Again without any log from the bot, I won't be able to figure it out.
If that happens, see whether TradingView docker is getting any request by executing the following command:
```
docker logs tradingview -f --tail=100
```

With 3rd issue, well. It obviously uses more cpu/memory because of the extra intensive requests.
I won't spend time on optimisation since it just works with RPi 4 without issue.

**Comment by elvishp2006** [comment]
@chrisleekr My configuration was to delete log with 30 minutes, I changed this for 2880 minutes, I will close the issue for now, if happen again I will report with logs

**Comment by chrisleekr** [comment]
@elvishp2006 

Yap. When it happens, it may be hard to find the exact log. 

If you can find the archive message. Good. Otherwise, just export logs of the symbol.

For the 2nd issue, I am releasing https://github.com/chrisleekr/binance-trading-bot/pull/375

Test it out whether it happens again.
I also disable periodic restarting in my server to check whether it happens or not.
