### ISSUE TITLE
Buy/Sell Grid Calculator

### ISSUE THREAD

**Issue by BramFr** [chrisleekr/binance-trading-bot#390]
I have read this thread (https://github.com/chrisleekr/binance-trading-bot
) several times and made a excel sheet to easy calculate your minimal profit.

But with my calculation (worst scenario) you dont have any profit. You loss some money.

[BinanceBot_Calculate.xlsx](https://github.com/chrisleekr/binance-trading-bot/files/7503459/BinanceBot_Calculate.xlsx)

Did i have made a mistake with the xlsx?

**Comment by chrisleekr** [comment]
I won't open excel file (for security reason). 
Please make Google Docs or something I can see in online.

**Comment by BramFr** [comment]
> I won't open excel file (for security reason). Please make Google Docs or something I can see in online.

Sure :) 
https://docs.google.com/spreadsheets/d/159wlTHJyNubXzNN6XtfY8Be13UmEvPu4k4bc5WAVlAE/edit?usp=sharing
You have edit permissions

**Comment by chrisleekr** [comment]
Your last price for Sell Grid #1 is not correct.
It does not set as the last buy limit price. It is calculating new last buy price based on the coin quantity and quote quantity (purchase amount). 

See this code for the reference:  https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTradeHelper/common.js#L514

I have calculated based on your excel sheet. The last buy price should be `92.06181644`

![image](https://user-images.githubusercontent.com/5715919/140907704-b253023d-8c3e-478a-be64-4acde7375f02.png)

In addition, Sell Grid #2 is not using the last sell limit price. Even if the sell grid #1 is executed, the last buy price won't be updated. 

Lastly, your sell configuration is expecting low profit. If you were intended, it's ok. Otherwise, you won't get much profits. You also don't subtract the commission. So take that into account.

**Comment by BramFr** [comment]
Ah thanks i understand.
I think based with this in my mined i made a mistake 
![image](https://user-images.githubusercontent.com/16082279/140908994-a0bfd415-b32a-4e20-af49-05e807442d42.png)
