### ISSUE TITLE
Why do you need to use a FIAT currency?

### ISSUE THREAD

**Issue by davegreengo** [chrisleekr/binance-trading-bot#40]
As title, just wondered why is there a need to use a FIAT market? I'd like to use ETH as my base coin, so I always end up back at that, and can trade with any ETH markets.

Is this not possible?

Thanks.

**Comment by chrisleekr** [comment]
Hi @davegreengo 

Technically, it should be possible.

However, I never tested and the frontend is very optimised to FIAT. 
I just prefer to use FIAT because it is easy to get dollar values. 

You are more than welcome to contribute to support other coins. :)

Please close the issue if you think it is resolved.

**Comment by davegreengo** [comment]
Thanks for the reply.... I *think* I've managed to hack it to allow it to work without FIAT, but wouldn't know where to begin with a PR to make it configurable and have the frontend display correct info etc.

Will have a look into it, may be a project for me 👍 

Thanks again for the quick reply.
