### ISSUE TITLE
Getting started for a newbie questions

### ISSUE THREAD

**Issue by Sshuichi** [chrisleekr/binance-trading-bot#415]
## Description
Amazing work! And I really want to grasp it fully, and make this thread a go-to thread for any new user, possibly a newbie like myself. 
Here are a bunch of questions I would like some clarification on: 

- The Symbol is BTCUSDT, does the buying action buy the USDT or BTC? 
- Is it possible to start the bot with a selling point instead of buying? If so how to do it? 
- Does the Grid system for buying goes step by step? # 1 then # 2 etc..? Does it loop on # 2 after it executes it? Does # 1 gets executed only once per symbol? 
- How does the LOW get defined, is it the Lowest per day? Or per hour? Is it configurable? 
- Imagine I have 100K USDT, and at a buying signal I want to buy all of it in BTC, how to configure that? Same if I have 3 BTC and I want to fully buy USDT? 
- Let's say I want to buy when the coin drops 0.3%, is it possible to stop the buying if I see that the drop slop is greater than 0.3%? Let's say it's 0.5% and I know that the next second it will drop by 0.2% so get the bot to buy at actual -0.7% instead of 0.3%. 
- The config mentions candles, I believe you mean those sticks in the graph: 
![image](https://user-images.githubusercontent.com/5939429/154838287-cb2633f4-4323-4cce-93ca-27c0e460a467.png)
If I set 20 candles, or 1h time span does High and Low calculate based on that? 

Thank you so much and looking forward to hearing back from you.

**Comment by chrisleekr** [comment]
I am really sorry for the late reply @Sshuichi 


- The Symbol is BTCUSDT, does the buying action buy the USDT or BTC?
   If the symbol pair is BTC/USDT, then buying will be trade with USDT

- Is it possible to start the bot with a selling point instead of buying? If so how to do it?
  If you already have enough coin, you can set the last buy price, which will monitor the coin based on that price.

- Does the Grid system for buying goes step by step? # 1 then # 2 etc..? Does it loop on # 2 after it executes it? Does # 1 gets executed only once per symbol?
  If the last buy price is manually set, then it will start from #2. If the bot executed grid trade #1, then it won't re-execute #1. You will see yellow checkbox on the grid.

- How does the LOW get defined, is it the Lowest per day? Or per hour? Is it configurable?
  The lowest price can be configured based on the interval and number of candles. For example, if you configure it as 1m/30, then the bot will determine the lowest price from 30 candles for 1 min candle. It will be real-time. What it means is if there is a new candle, then it will calculate from the latest candle.

- Imagine I have 100K USDT, and at a buying signal I want to buy all of it in BTC, how to configure that? Same if I have 3 BTC and I want to fully buy USDT?
  You can set the max purchase amount on the grid setting. 

- Let's say I want to buy when the coin drops 0.3%, is it possible to stop the buying if I see that the drop slop is greater than 0.3%? Let's say it's 0.5% and I know that the next second it will drop by 0.2% so get the bot to buy at actual -0.7% instead of 0.3%.
  If the bot is triggering the buy action, then it will follow the drop. 

- The config mentions candles, I believe you mean those sticks in the graph: If I set 20 candles, or 1h time span does High and Low calculate based on that?
   Yes, if you set 20/1h, then the lowest price would be calculated within 20 candles of 1-hour candle, so within 20 hours.
