### ISSUE TITLE
Redlock uncaught exceptions

### ISSUE THREAD

**Issue by rando128** [chrisleekr/binance-trading-bot#502]
I'm running v0.0.90 and I've received over 120 error messages in the last 10 days about various redlock issues. Despite the fact the bot doesn't crash, is there anything to worry about or does it affect the bot behaviour?

Here are examples of error types I've received:

`Unable to fully release the lock on resource "redlock:trailing-trade-closed-trades:USDT".
`

`Exceeded 4 attempts to lock the resource "redlock:auth-jwt-secret".
`

`Exceeded 4 attempts to lock the resource "redlock:trailing-trade-configurations:global".
`

`Unable to fully release the lock on resource "redlock:trailing-trade-common:exchange-info".
`

`Unable to fully release the lock on resource "redlock:trailing-trade-common:exchange-symbols".
`

`Unable to fully release the lock on resource "redlock:bot-lock:BTCUSDT".`

**Comment by habibalkhabbaz** [comment]
Hello @rando128 

It is solved in the latest version.
Kindly close the issue if you upgraded to latest version :)

**Comment by rando128** [comment]
Thx @habibalkhabbaz!

**Comment by rando128** [comment]
Hi @habibalkhabbaz, just got a flood of `Exceeded 4 attempts to lock the resource "redlock:auth-jwt-secret".` error messages this morning on 0.0.93.

**Comment by rando128** [comment]
I'm running MacOS with 8 symbols (and only 2 had trading enabled).

**Comment by habibalkhabbaz** [comment]
Did you receive messages such as the following?

```
Unable to fully release the lock on resource...
```

**Comment by rando128** [comment]
No. Only received `Exceeded 4 attempts to lock the resource "redlock:auth-jwt-secret"`

**Comment by habibalkhabbaz** [comment]
Hello @rando128 

Sorry for asking too many questions but I am still checking this because I couldn't reproduce the issue.

Does the bot running alone or you were trying to access the frontend or triggering any actions at the morning?

**Comment by rando128** [comment]
I was accessing the frontend and making some config changes.

**Comment by habibalkhabbaz** [comment]
Hello @rando128 

I tried to reproduce the issue but no luck from my side xD.

If it is happened to you again just write down the exact steps you followed here and I will check and fix it.

**Comment by rando128** [comment]
Sure. No problem. Thx for having tried anyway!

**Comment by dasbts** [comment]
It happened for me now, and have previously as well. I haven't taken any steps at all to make this happen, but an open position was just triggered to trail, and then this started showing up in Slack, followed by no trade happening so it's now still trailing.

**Comment by dasbts** [comment]
For me this happens pretty much as soon as the bot has run for more than a day without restarting it and I enter the bot. 

Usually it happens if I have a buy/sell trailing currently active. I don't know but I think (since it was 0.2% away) it happens when it tries to cancel a trade and give it a new price for example if the trailing buy trade keeps sinking in price (for a long scenario) and it cancels to update the buy price at a lower price. This then fails to use what I suppose is already locked by redis and it gives me all the following errors while failing to load the GUI (if I was already in the GUI it won't allow me back in usually until I restart the bot): 
Unable to fully release the lock on resource "redlock:auth-jwt-secret".
Exceeded 4 attempts to lock the resource "redlock:auth-jwt-secret".
Unable to fully release the lock on resource "redlock:trailing-trade-configurations:global".
Unable to fully release the lock on resource "redlock:trailing-trade-closed-trades:USDT".
And the last one in different currencies if not trading with USDT. 

Sometimes I also get this error (usually when changing the timeframe I watch my current profits from monthly to weekly in the top right GUI): 
Unable to fully release the lock on resource "redlock:trailing-trade-common:exchange-symbols".

It just keeps spamming this until I close the browser tab and I always have to restart the bot to fix it. Somehow when this happens it also seem to freeze the whole computer/server that I run the bot on, causing intense lag even tho I have a very big swapfile for extra VRAM.
