### ISSUE TITLE
Pagination not working after deleting symbols

### ISSUE THREAD

**Issue by Rayn0r** [chrisleekr/binance-trading-bot#506]
## Version

Version: v0.0.90 (48865a0)
Latest Version:
[v0.0.90](https://github.com/chrisleekr/binance-trading-bot/releases)

## Description

After deleting symbols from the list of coins to trade, pagination does not work any more.

## To Reproduce
1. Have at least 13 symbols in your list.
2. Remove one symbol from your list.
3. You will not be able to switch to the page containing your last symbol.

## Expected Behaviours

One should still be able to cycle through the page of coins displayed, in order to be able to delete them.

**Comment by habibalkhabbaz** [comment]
Hello @Rayn0r 

I understand that.
We have to count the number of the symbols from `trailing-trade-cache` instead of the global configuration.
Another possible solution is, we can remove the data from `trailing-trade-cache` so it will be reinitiated after applying the new monitoring symbols.
By doing one of these solutions, the pagination behavior will work as expected.

I will submit a PR to solve this when I have time.
