### ISSUE TITLE
Few dashboard card improvements

### ISSUE THREAD

**Issue by santoshbmath** [chrisleekr/binance-trading-bot#93]
### Is your proposal related to a problem?
No, but suggesting few improvements.

### Describe the solution you'd like
Here are few enhancements i am suggesting,
1. Change minimize icon to close icon as it closes/removes the card from the dashboard.
2. Move "Settings" icon in card header along with close icon.
3. Remove "Balance...." row altogether as the symbol is already present in header.
4. Club action and current price in one section. Because based on current price action will be updated.

**Comment by chrisleekr** [comment]
Thanks for suggestions.

> 1. Change minimize icon to close icon as it closes/removes the card from the dashboard.

Oh, good point. I will change to `X` rather than `-`.

> 2. Move "Settings" icon in card header along with close icon.

Ok, good point again.

> 3. Remove "Balance...." row altogether as the symbol is already present in header.

Well, if I have multiple coins and I should open the Account Balance accordion and find the coin balance. I think we can keep it to make less mouse click?

> 4. Club action and current price in one section. Because based on current price action will be updated.

I tried to put the current price in the relevant sections as below. Are you saying, remove those current price rows and put with Action row? Wouldn't be annoying if you keep moving your eyes to compare with other prices?
![image](https://user-images.githubusercontent.com/5715919/114979356-12281380-9ece-11eb-8b9e-1f913a0139c5.png)

**Comment by chrisleekr** [comment]
Hey guys,

I have updated the frontend in the pull request for points 1 and 2. 

![image](https://user-images.githubusercontent.com/5715919/115189247-8a3e4580-a129-11eb-951a-2c80e8e53a78.png)

Points 3/4 will not be fixed. 
This issue will be closed once the PR is merged.
